#!/bin/bash

if ! [ which checknullargumentandadderror > /dev/null ]; then

fi

wpdbchapi(){
	declare -a errors

	if [ -z $1 ]; then
		errors+=('You must provides the first argument as the path to the wp-config.php file')
	fi

	if [ -z ]
}
