#!/bin/bash

wpdbnamech() {
    declare -a errors

    if ! [ `which wpdbchapi` ]; then
        echo 'wpdbnamech error: You need first have in the system the wpdbchapi utility to proced. Operation caceled.'
        return
    fi

    if [ ${#1} -eq 0 ]; then
        errors+=('wpdbnamech error: You need the first argument to be the path to wp-config.php file.')
    elif ! [ -f $1 ]; then
        errors+=('wpdbnamech error: The first argument provided - which must be the path to the wp-config.php - was not found.') 
    elif ! [ -w $1 ]; then
        errors+=('wpdbnamech error: The file provided in the first argument is not writable by the current user.')
    fi

    if [ -z $2 ]; then
        errors+=('wpbdnamech error: the second argument was not provided: must be the old term to be replaced.')
    fi

    if [ -z $3 ]; then
        errors+=('wpbdnamech error: the third argument was not provided: must be the new term to replace.')
    fi

    errors_count=${#errors[@]}
    if [ $errors_count -gt 0 ]; then
        for i in $(seq 0 $(expr $errors_count - 1)); do
            echo ${errors[$i]}
        done
        echo wpdbnamech: operation aborted
        return
    fi

    wpdbchapi $1 'DB_NAME' $2 $3
}

wpdbnamech $1 $2 $3
